apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f helm.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f helm.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/camunda-animal-picture-app-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: camunda-animal-picture-app-frontend:latest
          imagePullPolicy: Never
          name: frontend
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
